services:
  dommern-db:
    container_name: dommern-db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=race'
      - 'POSTGRES_PASSWORD=user'
      - 'POSTGRES_USER=password'
    ports:
      - '5432'
    network_mode: host
