services:
  dommern:
    container_name: dommern
    platform: linux/arm64
    build: .
    restart: unless-stopped
    network_mode: host
    depends_on:
      dommern-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: production
      DOMMERN_MAIL: true

  db: &basedb
    container_name: dommern-db
    image: 'postgres:17.4'
    environment:
      - 'POSTGRES_DB=dommern'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    network_mode: host
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready --port 5432 --username=user --dbname=dommern'" ]
      interval: 2s
      retries: 5
      timeout: 1s

  dommern-db:
    <<: *basedb
    platform: linux/arm64
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql