x-app: &baseapp
  restart: unless-stopped
  network_mode: host
  environment:
    SPRING_PROFILES_ACTIVE: production
    SPRING_MAIL_USERNAME: ${EMAIL-USER}
    SPRING_MAIL_PASSWORD: ${EMAIL-PW}

services:
  app:
    <<: *baseapp
    platform: linux/amd64
    container_name: app
    build: .
    depends_on:
      db:
        condition: service_healthy

  dommern:
    <<: *baseapp
    platform: linux/arm64
    container_name: dommern
    image: ghcr.io/vejmon/dommern:latest
    depends_on:
      dommern-db:
        condition: service_healthy

  db: &basedb
    container_name: dommern-db
    platform: linux/amd64
    image: 'postgres:17.4'
    environment:
      - 'POSTGRES_DB=dommern'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    network_mode: host
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready --port 5432 --username=user --dbname=dommern'" ]
      interval: 2s
      retries: 5
      timeout: 1s

  dommern-db:
    <<: *basedb
    platform: linux/arm64
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql