server:
  shutdown: immediate

spring:
  application:
    name: dommern
  jpa:
    database: POSTGRESQL
    open-in-view: false
    show-sql: false
  datasource:
    username: dommern_api_user
    password: password
    url: jdbc:postgresql://localhost:5432/dommern
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      idle-timeout: 15000
      maximum-pool-size: 10
      minimum-idle: 5
  flyway:
    enabled: true
    user: dommern_api_flyway
    password: password
    url: jdbc:postgresql://localhost:5432/dommern
  mail:
    password: ${EMAIL_PW:}
    username: ${EMAIL_USER:}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 50MB
      clean-history-on-start: true
  level:
    root: INFO

---
spring:
  config.activate.on-profile: production
  pi4j:
    gpio:
      pins: [ 4, 17, 24, 25 ] # BCM pin identifiers
      pull: off # off, up or down
