[versions]
pi4j = '3.0.3'

[libraries]
spring-boot-starter = { module = 'org.springframework.boot:spring-boot-starter' }
spring-boot-starter-web = { module = 'org.springframework.boot:spring-boot-starter-web' }
spring-boot-starter-data-jpa = { module = 'org.springframework.boot:spring-boot-starter-data-jpa' }
spring-boot-starter-data-rest = { module = 'org.springframework.boot:spring-boot-starter-data-rest' }
spring-boot-starter-thymeleaf = { module = 'org.springframework.boot:spring-boot-starter-thymeleaf' }
spring-boot-starter-mail = { module = 'org.springframework.boot:spring-boot-starter-mail' }
springdoc-openapi-webmvc-ui = { module = 'org.springdoc:springdoc-openapi-starter-webmvc-ui', version = '2.8.14'}

flyway-core = { module = 'org.flywaydb:flyway-core' }
flyway-database-postgresql = { module = 'org.flywaydb:flyway-database-postgresql' }
jakarta-validation-api = { module = 'jakarta.validation:jakarta.validation-api' }

pi4j-core = { module = 'com.pi4j:pi4j-core', version.ref = 'pi4j' }
pi4j-plugin-raspberrypi = { module = 'com.pi4j:pi4j-plugin-raspberrypi', version.ref = 'pi4j' }
pi4j-plugin-gpiod = { module = 'com.pi4j:pi4j-plugin-gpiod', version.ref = 'pi4j' }
pi4j-plugin-mock = { module = 'com.pi4j:pi4j-plugin-mock', version.ref = 'pi4j' }


# test modules
spring-boot-testcontainers = { module = 'org.springframework.boot:spring-boot-testcontainers' }
spring-boot-starter-test = { module = 'org.springframework.boot:spring-boot-starter-test' }
mockito-core = {module = 'org.mockito:mockito-core', version = '5.21.0'}
mockito-inline = { module = 'org.mockito:mockito-inline', version = '5.2.0' }
junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter' }
testcontainers-junit-jupiter = { module = 'org.testcontainers:junit-jupiter' }
testcontainers-postgresql = { module = 'org.testcontainers:postgresql' }


[bundles]
pi4j = ['pi4j-core', 'pi4j-plugin-gpiod', 'pi4j-plugin-mock', 'pi4j-plugin-raspberrypi'
]
spring-starters = ['spring-boot-starter', 'spring-boot-starter-data-jpa', 'spring-boot-starter-data-rest',
    'spring-boot-starter-thymeleaf', 'spring-boot-starter-web', 'springdoc-openapi-webmvc-ui', 'spring-boot-starter-mail'
]
db = ['flyway-core', 'flyway-database-postgresql', 'jakarta-validation-api'
]
test = ['mockito-inline', 'mockito-core', 'junit-jupiter', 'testcontainers-junit-jupiter', 'testcontainers-postgresql',
    'spring-boot-starter-test', 'spring-boot-testcontainers'
]
