name: Build, Test and deploy Dommern

on:
  push:
    branches:
      - feat/ci-cd-raspberry-pi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build and test dommern project
      uses : ./.github/actions/gradle-build

    - name: Build and push Docker image to GHCR
      uses: ./.github/actions/docker-build

    - name: Deploy to Pi using Tailscale
      uses: ./.github/actions/tailscale-deploy
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
        ssh-user: vemu
        ssh-host: ${{ secrets.TAILSCALE_PI_HOST }}
        app-path: ~/Dommern/dommern

