name: Build, Test and deploy Dommern

on:
  push:
    branches:
      - feat/ci-cd-raspberry-pi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build and test dommern project
      uses : ./.github/actions/gradle-build

    - name: Build and push Dommern-db image to GHCR
      uses: ./.github/actions/docker-build
      with:
        service: dommern-db
        local_image: dommern-db
        ghcr_image: dommern/dommern-db

    - name: Build and push Dommern image to GHCR
      uses: ./.github/actions/docker-build
      with:
        service: dommern
        local_image: dommern
        ghcr_image: dommern/dommern

    - name: Deploy to Pi using Tailscale
      uses: ./.github/actions/tailscale-deploy
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}

